import type { FieldType } from '@/types'
import type { EnumValueMeta, PropertyMeta } from './types'

/** FieldType 全部取值(与 types/schema.ts 的 FieldType 联合保持一致,由穷举键表单测守护) */
export const FIELD_TYPE_VALUES: EnumValueMeta[] = [
  { value: 'text', label: '文本' },
  { value: 'number', label: '数字' },
  { value: 'date', label: '日期' },
  { value: 'datetime', label: '日期时间' },
  { value: 'boolean', label: '布尔' },
  { value: 'select', label: '单选枚举' },
  { value: 'multi-select', label: '多选枚举' },
  { value: 'status', label: '状态枚举', desc: 'select 的语义别名,支持 statusMap 取色' },
  { value: 'fk', label: '外键引用' },
  { value: 'one-to-many', label: '一对多关联' },
  { value: 'many-to-many', label: '多对多关联' },
  { value: 'reverse-ref', label: '反向引用' },
  { value: 'formula', label: '公式' },
  { value: 'percent', label: '百分比' },
  { value: 'currency', label: '货币' },
  { value: 'money', label: '金额' },
  { value: 'phone', label: '手机号' },
  { value: 'email', label: '邮箱' },
  { value: 'url', label: '链接' },
  { value: 'image', label: '图片' },
  { value: 'mediaImage', label: '媒体图片' },
  { value: 'attachment', label: '附件' },
  { value: 'json', label: 'JSON' },
  { value: 'action', label: '行操作' },
]

const NUMERIC_TYPES: FieldType[] = ['number', 'currency', 'money', 'percent']
const ENUM_TYPES: FieldType[] = ['select', 'multi-select', 'status']
const ALL: FieldType[] | 'all' = 'all'

/**
 * FieldSchema 穷举键表:类型层面强制与 types/schema.ts 的 FieldSchema 字段一一对应。
 * FieldSchema 新增属性而未在此登记时 type-check 直接失败(防漏第一道闸)。
 */
export const FIELD_SCHEMA_KEYS: Record<keyof import('@/types').FieldSchema, true> = {
  id: true,
  name: true,
  key: true,
  type: true,
  label: true,
  required: true,
  readonly: true,
  visibleWhen: true,
  editableWhen: true,
  defaultValue: true,
  placeholder: true,
  description: true,
  order: true,
  width: true,
  visible: true,
  fixed: true,
  sortable: true,
  filterable: true,
  filterCandidates: true,
  validationRules: true,
  permission: true,
  formula: true,
  dynamicMax: true,
  options: true,
  statusMap: true,
  displayStyle: true,
  targetModule: true,
  editMode: true,
  quickCreate: true,
  displayField: true,
  group: true,
  mergeCells: true,
  category: true,
  nullableFilter: true,
  rowAction: true,
  aggregation: true,
  countCondition: true,
  treatAsEmpty: true,
  prefixStr: true,
  suffixStr: true,
  decimal: true,
  decimalMode: true,
  maxDecimal: true,
  switchMode: true,
  trueLabel: true,
  falseLabel: true,
  trueLabelClass: true,
  falseLabelClass: true,
  defaultDateOffset: true,
  previousKeys: true,
  relationConfig: true,
  reverseRefConfig: true,
  highlightStyle: true,
}

/** FieldSchema 全量属性元数据(51 项,顺序即文档表格默认顺序) */
export const FIELD_META: PropertyMeta[] = [
  {
    key: 'id', target: 'field', label: '字段 ID', group: 'basic', appliesTo: ALL, kind: 'string',
    required: true, surfaces: [],
    description: '字段唯一标识。当前与 key 同值使用,保留独立字段以备分离语义标识与数据键。',
  },
  {
    key: 'name', target: 'field', label: '字段名', group: 'basic', appliesTo: ALL, kind: 'string',
    required: true, surfaces: [],
    description: '字段的内部名称。引擎渲染以 label 为准,name 主要用于检索与运维语义。',
  },
  {
    key: 'key', target: 'field', label: '数据键', group: 'basic', appliesTo: ALL, kind: 'string',
    required: true, surfaces: [],
    description: '记录数据中的字段键(record.fields[key]),列渲染、筛选、排序、编辑保存全部以它定位。重命名历史键请配合 previousKeys 迁移。',
    related: ['previousKeys'],
    example: 'amount',
  },
  {
    key: 'type', target: 'field', label: '字段类型', group: 'basic', appliesTo: ALL, kind: 'enum',
    enumValues: FIELD_TYPE_VALUES, default: 'text', required: true,
    surfaces: ['render', 'inline-edit', 'filter', 'form', 'card'],
    description: '决定渲染器、编辑器、筛选方式与表单控件的字段类型。切换类型后本面板会按新类型重新过滤适用属性。',
  },
  {
    key: 'label', target: 'field', label: '列标题', group: 'basic', appliesTo: ALL, kind: 'string',
    required: true, surfaces: ['render', 'form', 'card'],
    description: '列表头、卡片标签、表单标签显示的标题文本。',
    example: '报销金额',
  },
  {
    key: 'required', target: 'field', label: '必填', group: 'basic', appliesTo: ALL, kind: 'boolean',
    default: false, required: true, surfaces: ['form', 'card'],
    description: '表单必填标记。当前在快速创建弹窗中强制校验;创建视图以 UI 必填星号提示(校验统一见改进计划批次 D)。',
    related: ['validationRules'],
  },
  {
    key: 'readonly', target: 'field', label: '绝对只读', group: 'basic', appliesTo: ALL, kind: 'boolean',
    default: false, required: true, surfaces: ['inline-edit', 'form', 'card'],
    description: '绝对禁止编辑:行内编辑与表单编辑全部禁用,与 editMode=limited 的「仅禁止行内编辑」相区分。',
    related: ['editMode'],
  },
  {
    key: 'visibleWhen', target: 'field', label: '条件显示', group: 'condition', appliesTo: ALL, kind: 'condition',
    surfaces: ['render', 'form', 'card'],
    description: '条件表达式,逐行以行数据为 record 上下文求值,控制字段显示。支持 and/or/not 组合与 15 种算子。',
    example: { left: { record: 'status' }, operator: 'eq', right: { value: 'active' } },
  },
  {
    key: 'editableWhen', target: 'field', label: '条件可编辑', group: 'condition', appliesTo: ALL, kind: 'condition',
    surfaces: ['inline-edit', 'form', 'card'],
    description: '条件表达式,求值通过才允许编辑;与 readonly、permission.editable、editMode 叠加生效。',
    example: { left: { record: 'status' }, operator: 'neq', right: { value: 'archived' } },
  },
  {
    key: 'defaultValue', target: 'field', label: '默认值', group: 'basic', appliesTo: ALL, kind: 'unknown',
    surfaces: ['form', 'card'],
    description: '新建记录(创建视图/卡片创建)时字段的初始值;日期字段请改用 defaultDateOffset 表达相对今天。',
    related: ['defaultDateOffset'],
    example: 0,
  },
  {
    key: 'placeholder', target: 'field', label: '占位提示', group: 'edit', appliesTo: ALL, kind: 'string',
    surfaces: ['inline-edit', 'form', 'card'],
    description: '编辑控件内的占位提示文本。',
    example: '请输入备注',
  },
  {
    key: 'description', target: 'field', label: '字段描述', group: 'basic', appliesTo: ALL, kind: 'string',
    surfaces: ['form', 'card'],
    description: '字段辅助说明文本,当前在卡片创建视图中作为字段提示(field-hint)渲染。',
    example: '含税金额,不含运费',
  },
  {
    key: 'order', target: 'field', label: '排序号', group: 'display', appliesTo: ALL, kind: 'number',
    required: true, surfaces: ['render', 'card'],
    description: '字段在列表与卡片中的显示顺序,从小到大排列。',
    example: 3,
  },
  {
    key: 'width', target: 'field', label: '列宽(px)', group: 'display', appliesTo: ALL, kind: 'number',
    surfaces: ['render'],
    description: '固定列宽(像素)。未声明时进入弹性列宽通道(minWidth 120,随容器伸缩)。用户可在列设置面板中覆盖。',
    example: 160,
  },
  {
    key: 'visible', target: 'field', label: '默认可见', group: 'display', appliesTo: ALL, kind: 'boolean',
    default: true, required: true, surfaces: ['render', 'card'],
    description: '字段默认是否显示;用户可在列设置面板中覆盖,覆盖结果持久化到 UserViewConfig。',
  },
  {
    key: 'fixed', target: 'field', label: '固定列', group: 'display', appliesTo: ALL, kind: 'enum',
    enumValues: [
      { value: 'left', label: '固定在左侧' },
      { value: 'right', label: '固定在右侧' },
    ],
    surfaces: ['render'],
    description: '将该列固定在表格左侧或右侧(横向滚动时不随动)。用户可在列设置面板中覆盖。',
  },
  {
    key: 'sortable', target: 'field', label: '可排序', group: 'display', appliesTo: ALL, kind: 'boolean',
    default: false, required: true, surfaces: ['render'],
    description: '列头展示排序入口,排序为服务端单列排序(sort 参数随 list 请求下发)。排序状态变更会持久化到 UserViewConfig。',
  },
  {
    key: 'filterable', target: 'field', label: '可筛选', group: 'filter', appliesTo: ALL, kind: 'boolean',
    default: false, required: true, surfaces: ['filter'],
    description: '列头展示筛选与排序弹层入口;筛选条件 AND 合并后随 list 请求下发(服务端过滤契约)。',
    related: ['filterCandidates', 'nullableFilter'],
  },
  {
    key: 'filterCandidates', target: 'field', label: '候选值筛选模式', group: 'filter', appliesTo: ALL, kind: 'boolean',
    surfaces: ['filter'],
    description: 'Excel 式显式候选值模式。数值/日期字段缺省走关键词/时间段筛选,声明后覆盖为去重候选值列表(datetime 由服务端按天分桶);文本/枚举/外键列无需声明即默认候选值优先。',
    related: ['filterable'],
  },
  {
    key: 'nullableFilter', target: 'field', label: '空值筛选项', group: 'filter', appliesTo: ALL, kind: 'boolean',
    surfaces: ['filter'],
    description: '筛选面板中提供「为空/不为空」三态筛选;筛选栏(SchemaFilterBar)据此展示空值运算。',
    related: ['filterable'],
  },
  {
    key: 'validationRules', target: 'field', label: '校验规则', group: 'edit', appliesTo: ALL, kind: 'rules',
    surfaces: ['form', 'inline-edit'],
    description: '校验规则数组(type: required/min/max/minLength/maxLength/pattern/custom,message + level error|warning)。当前实际生效范围:快速创建弹窗;行内编辑仅数值精度校验,创建视图暂未执行(改进计划批次 D 统一三入口)。',
    example: [{ type: 'min', value: 0, message: '不能为负数', level: 'error' }],
  },
  {
    key: 'permission', target: 'field', label: '字段权限', group: 'condition', appliesTo: ALL, kind: 'object',
    surfaces: ['render', 'inline-edit', 'form', 'card'],
    description: '字段级权限 { visible, editable, roleBased }。visible=false 整列不渲染;editable=false 禁止行内编辑;roleBased 角色映射已声明、引擎暂未消费(改进计划批次 G)。',
    example: { visible: true, editable: false },
  },
  {
    key: 'formula', target: 'field', label: '公式配置', group: 'formula', appliesTo: ['formula'], kind: 'object',
    surfaces: ['render', 'card'],
    description: '公式字段配置 { fieldKey, expression, dependencies, resultType, aggregation },expression 为 mathjs 表达式,逐行求值渲染;引擎自带循环依赖检测。',
    example: { fieldKey: 'total', expression: 'price * qty', dependencies: ['price', 'qty'], resultType: 'number' },
  },
  {
    key: 'dynamicMax', target: 'field', label: '动态上限', group: 'formula', appliesTo: NUMERIC_TYPES, kind: 'object',
    surfaces: ['form', 'card'],
    description: '数值动态上限 { enabled, sourceField, ratio, mode: hard|soft, messageTemplate }:以同记录另一字段(surceField×ratio)为上限,hard 拦截提交、soft 仅提示。',
    example: { enabled: true, sourceField: 'budget', ratio: 1, mode: 'soft', messageTemplate: '不可超出预算 {max}' },
  },
  {
    key: 'options', target: 'field', label: '枚举选项', group: 'basic', appliesTo: ENUM_TYPES, kind: 'options',
    surfaces: ['render', 'inline-edit', 'filter', 'form', 'card'],
    description: '枚举选项数组 { label, value, color?, disabled? }。color 取语义色调(primary/success/warning/danger/info)或任意 CSS 颜色,渲染为彩色标签;同时作为列头候选值筛选与编辑下拉的数据源。',
    example: [
      { label: '待审批', value: 'pending', color: 'warning' },
      { label: '已通过', value: 'approved', color: 'success' },
    ],
  },
  {
    key: 'statusMap', target: 'field', label: '状态取色表', group: 'display', appliesTo: ENUM_TYPES, kind: 'object',
    surfaces: ['render', 'card'],
    description: '枚举值 → 颜色的字段级取色表(Record<string,string>);options[].color 优先级更高,未命中时回退 statusMap。',
    related: ['options'],
    example: { pending: 'warning', approved: 'success' },
  },
  {
    key: 'displayStyle', target: 'field', label: '值展示样式', group: 'display', appliesTo: [...ENUM_TYPES, 'fk'], kind: 'enum',
    enumValues: [
      { value: 'tag', label: '胶囊/彩色标签', desc: '枚举按 options[].color 取色,select/fk 渲染胶囊' },
      { value: 'plain', label: '纯文本', desc: '统一为普通字色文本,无底色描边(表格风格统一场景)' },
    ],
    surfaces: ['render'],
    description: '字段级值展示覆盖(docs/20):未声明时跟随引擎 appearance.valueDisplay。用于关键列在全局 plain 下保留彩色标签(如审核状态列)。',
    related: ['options', 'statusMap'],
  },
  {
    key: 'targetModule', target: 'field', label: '目标模块', group: 'relation', appliesTo: ['fk'], kind: 'string',
    surfaces: ['render', 'inline-edit', 'form', 'card'],
    description: 'fk 字段引用的目标模块 ID:候选值经 candidateService 按目标模块拉取,标签解析走 candidateService + getDetail 兜底;quickCreate 快速创建也按目标模块渲染必选字段。',
    related: ['quickCreate'],
    example: 'module-user',
  },
  {
    key: 'editMode', target: 'field', label: '编辑模式', group: 'edit', appliesTo: ALL, kind: 'enum',
    enumValues: [
      { value: 'standard', label: '常规(行内+表单)', desc: '默认' },
      { value: 'limited', label: '有限编辑', desc: '禁止行内编辑,仅创建/专用通道可改;后端不强制拦截' },
    ],
    default: 'standard', surfaces: ['inline-edit'],
    description: 'standard=常规(行内+表单);limited=有限编辑(禁止行内编辑,仅创建/专用通道可改)。与 readonly 的绝对禁止相区分。',
    related: ['readonly'],
  },
  {
    key: 'quickCreate', target: 'field', label: '快速创建入口', group: 'edit', appliesTo: ['fk'], kind: 'boolean',
    default: false, surfaces: ['inline-edit', 'form'],
    description: 'fk 下拉底部提供「+ 新建」入口:打开弹层按目标模块必选字段快速创建,创建后自动选中;目标无独立模块定义时降级为仅填 name。',
    related: ['targetModule'],
  },
  {
    key: 'displayField', target: 'field', label: '显示字段(预留)', group: 'relation', appliesTo: ['fk'], kind: 'string',
    surfaces: [],
    description: '预留配置:fk 显示文本字段。当前版本 fk 标签由 candidateService 候选数据与 getDetail 兜底解析决定,引擎未消费该属性(关系字段的显示字段走 relationConfig.displayField)。',
    related: ['relationConfig'],
  },
  {
    key: 'group', target: 'field', label: '表头分组', group: 'basic', appliesTo: ALL, kind: 'string',
    surfaces: ['render'],
    description: '多级表头分组标题(docs/19 F3):声明后与相邻同组字段合并为一个分组表头(colgroup),标题即本值;未声明字段的表头保持单层。',
    example: '金额信息',
  },
  {
    key: 'mergeCells', target: 'field', label: '相同值合并', group: 'display', appliesTo: ALL, kind: 'boolean',
    surfaces: ['render'],
    description: '相同值合并单元格(docs/19 F5):声明后列表中相邻同值行在该列纵向合并(rowspan),树形模块暂不支持;适合状态、地区等低基数列。',
    example: true,
  },
  {
    key: 'category', target: 'field', label: '分类(预留)', group: 'basic', appliesTo: ALL, kind: 'string',
    surfaces: [],
    description: '预留配置:当前版本引擎未消费,仅作语义分类标注。',
  },
  {
    key: 'rowAction', target: 'field', label: '行操作配置', group: 'display', appliesTo: ['action'], kind: 'object',
    surfaces: ['render'],
    description: 'action 字段的行级按钮配置 { type: popup-schema|form-submit|export|delete|custom, label, icon?, visibleWhen?, danger?, target? };visibleWhen 逐行求值控制按钮显隐,danger 渲染红字。delete 类型由引擎内置渲染(见 ModuleSchema.operations)。',
    example: { type: 'custom', label: '停用', danger: true, visibleWhen: { left: { record: 'status' }, operator: 'eq', right: { value: 'active' } } },
  },
  {
    key: 'aggregation', target: 'field', label: '聚合统计', group: 'display', appliesTo: NUMERIC_TYPES, kind: 'enum',
    enumValues: [
      { value: 'sum', label: '求和' },
      { value: 'average', label: '平均' },
      { value: 'count', label: '计数' },
      { value: 'max', label: '最大' },
      { value: 'min', label: '最小' },
    ],
    surfaces: ['render'],
    description: '在表格下方聚合统计条中对该列计算;当前基于客户端、仅统计当前页数据(改进计划批次 C/E 评估全量口径)。',
    related: ['countCondition', 'treatAsEmpty'],
    example: 'sum',
  },
  {
    key: 'countCondition', target: 'field', label: '计数条件', group: 'display', appliesTo: ALL, kind: 'enum',
    enumValues: [
      { value: 'empty', label: '统计空值数' },
      { value: 'notEmpty', label: '统计非空数' },
    ],
    surfaces: ['render'],
    description: '仅 aggregation=count 时有效:统计空值(empty)或非空(notEmpty)的记录数。',
    related: ['aggregation'],
  },
  {
    key: 'treatAsEmpty', target: 'field', label: '视同空值', group: 'display', appliesTo: ALL, kind: 'string[]',
    surfaces: ['render'],
    description: '聚合统计与草稿生命周期中,命中该列表中任意值的记录视同空值(不参与 sum/average 等)。',
    related: ['aggregation'],
    example: [0, 'N/A'],
  },
  {
    key: 'prefixStr', target: 'field', label: '数值前缀', group: 'display', appliesTo: NUMERIC_TYPES, kind: 'string',
    surfaces: ['form'],
    description: '表单数值编辑器(NumberEditor)内渲染的前缀饰文本,如货币符号。',
    example: '¥',
  },
  {
    key: 'suffixStr', target: 'field', label: '数值后缀', group: 'display', appliesTo: NUMERIC_TYPES, kind: 'string',
    surfaces: ['form'],
    description: '表单数值编辑器(NumberEditor)内渲染的后缀饰文本;percent 类型自带「%」后缀。',
    example: '元',
  },
  {
    key: 'decimal', target: 'field', label: '小数位数', group: 'display', appliesTo: NUMERIC_TYPES, kind: 'number',
    surfaces: ['render', 'inline-edit', 'form', 'card'],
    description: '数值/百分比/货币的小数位数:number 无默认,currency 默认 2,percent 默认 0。行内编辑据此做精度校验。',
    related: ['decimalMode', 'maxDecimal'],
    example: 2,
  },
  {
    key: 'decimalMode', target: 'field', label: '小数精度模式', group: 'display', appliesTo: NUMERIC_TYPES, kind: 'enum',
    enumValues: [
      { value: 'fixed', label: '固定位数(补零)', desc: '默认' },
      { value: 'max', label: '最多位数(省尾零)' },
      { value: 'range', label: '区间( decimal ~ maxDecimal )' },
    ],
    default: 'fixed', surfaces: ['render', 'form', 'card'],
    description: 'fixed=固定位数补零;max=最多 decimal 位、末尾零省略;range=最少 decimal 位、最多 maxDecimal 位。',
    related: ['decimal', 'maxDecimal'],
  },
  {
    key: 'maxDecimal', target: 'field', label: '小数上限位数', group: 'display', appliesTo: NUMERIC_TYPES, kind: 'number',
    surfaces: ['render'],
    description: '仅 decimalMode=range 时有效:小数位上限。',
    related: ['decimal', 'decimalMode'],
    example: 4,
  },
  {
    key: 'switchMode', target: 'field', label: '布尔展示模式', group: 'display', appliesTo: ['boolean'], kind: 'enum',
    enumValues: [
      { value: 'switch', label: '切换开关', desc: '默认' },
      { value: 'radio', label: '圆形勾选框' },
    ],
    default: 'switch', surfaces: ['render', 'inline-edit', 'card'],
    description: '布尔字段渲染为切换开关(switch)或圆形勾选框(radio)。',
  },
  {
    key: 'trueLabel', target: 'field', label: '真值标签', group: 'display', appliesTo: ['boolean'], kind: 'string',
    default: '是', surfaces: ['render', 'card'],
    description: '布尔字段值为 true 时的显示文本,默认「是」。',
    related: ['trueLabelClass', 'falseLabel'],
    example: '已启用',
  },
  {
    key: 'falseLabel', target: 'field', label: '假值标签', group: 'display', appliesTo: ['boolean'], kind: 'string',
    default: '否', surfaces: ['render', 'card'],
    description: '布尔字段值为 false 时的显示文本,默认「否」。',
    related: ['falseLabelClass', 'trueLabel'],
    example: '已停用',
  },
  {
    key: 'trueLabelClass', target: 'field', label: '真值样式类', group: 'display', appliesTo: ['boolean'], kind: 'string',
    surfaces: ['render', 'card'],
    description: 'true 标签的 CSS 类名;不声明时默认绿色(cell-boolean--yes),可传引擎预设 cell-boolean--neutral(灰)或业务自有类。',
    related: ['trueLabel'],
  },
  {
    key: 'falseLabelClass', target: 'field', label: '假值样式类', group: 'display', appliesTo: ['boolean'], kind: 'string',
    surfaces: ['render', 'card'],
    description: 'false 标签的 CSS 类名;不声明时默认红色(cell-boolean--no),可传引擎预设 cell-boolean--neutral(灰)或业务自有类。',
    related: ['falseLabel'],
  },
  {
    key: 'defaultDateOffset', target: 'field', label: '默认日期偏移(天)', group: 'basic', appliesTo: ['date', 'datetime'], kind: 'number',
    surfaces: ['form', 'card'],
    description: '新建记录时日期字段的默认值偏移:0=今天,正数=未来,负数=过去。声明后优先于 defaultValue。',
    related: ['defaultValue'],
    example: 7,
  },
  {
    key: 'previousKeys', target: 'field', label: '历史键(since 2.0)', group: 'basic', appliesTo: ALL, kind: 'string[]',
    since: '2.0', surfaces: [],
    description: '字段重命名前的旧 key 列表:引擎加载时自动把旧键数据映射到当前 key,配合 SchemaMigration 实现平滑升级。',
    related: ['key'],
    example: ['amount_old'],
  },
  {
    key: 'relationConfig', target: 'field', label: '关联配置', group: 'relation', appliesTo: ['one-to-many', 'many-to-many'], kind: 'object',
    surfaces: ['render', 'inline-edit', 'form', 'card'],
    description: '一对多/多对多关联配置 { targetModule, displayField, extraFields? }:渲染可点击的关联摘要,经 relationService 维护关联关系;extraFields 为关联表连带字段(如数量、单价)。',
    example: { targetModule: 'module-invoice', displayField: 'name' },
  },
  {
    key: 'reverseRefConfig', target: 'field', label: '反向引用配置', group: 'relation', appliesTo: ['reverse-ref'], kind: 'object',
    surfaces: ['render', 'card'],
    description: '反向引用配置 { sourceModules, relationFieldKey }:展示哪些源模块的记录通过 relationFieldKey 关联字段引用了当前记录(只读统计视图)。',
    example: { sourceModules: ['module-ap'], relationFieldKey: 'supplier' },
  },
  {
    key: 'highlightStyle', target: 'field', label: '筛选高亮样式', group: 'filter', appliesTo: ALL, kind: 'string',
    surfaces: ['render', 'card'],
    description: '文本包含式筛选命中片段的高亮 CSS 样式,默认黄色背景(如 background:#fff3b0)。',
    example: 'background:#ffe58f',
  },
]
